#!/usr/bin/env python3
import sys
from dataclasses import dataclass
from os.path import dirname
from pathlib import Path
from subprocess import check_call

import yaml

BASEDIR = Path(dirname(sys.argv[0]))


def check_call_verbose(argv, **kwargs):
    print("+", argv, file=sys.stderr)
    check_call(argv, **kwargs)


def ensure_key(priv: Path):
    if priv.exists():
        return
    priv.parent.mkdir(parents=True, exist_ok=True)
    check_call_verbose(["ssh-keygen", "-t", "ed25519", "-f", str(priv), "-N", ""])


@dataclass
class Container:
    host: str
    name: str
    path: str

    @property
    def dev_ssh(self):
        return BASEDIR / "dev-ssh" / self.name

    @property
    def host_priv(self):
        return self.dev_ssh / "ssh_host_ed25519_key"

    @property
    def host_pub(self):
        return self.host_priv.with_suffix(".pub")


def main():
    cfg = yaml.safe_load((BASEDIR / "agentic-dev.yml").read_text())
    containers = [
        Container(host=host, name=container, path=container_cfg["path"])
        for host, host_cfg in cfg["hosts"].items()
        for container, container_cfg in host_cfg["containers"].items()
    ]

    # Generate keys.
    agent_ssh = BASEDIR / "agent" / "home" / ".ssh"
    agent_priv = agent_ssh / "id_ed25519"
    agent_pub = agent_ssh / "id_ed25519.pub"
    agent_hosts = agent_ssh / "known_hosts"
    agent_config = agent_ssh / "config"
    ensure_key(agent_priv)
    for container in containers:
        ensure_key(container.host_priv)

    # Generate ssh client config.
    agent_config.write_text(
        "\n".join(
            f"Host {container.name}\n"
            f"    ProxyCommand socat - "
            f"UNIX-CONNECT:/home/user/.ssh/sshd-{container.name}.sock\n"
            f"    User user\n"
            for container in containers
        )
    )

    # Prepare keys for distribution.
    known_hosts = []
    for container in containers:
        (container.dev_ssh / "authorized_keys").write_bytes(agent_pub.read_bytes())
        (container.dev_ssh / "sshd_config").write_text("""\
Port 2222
HostKey /home/user/.ssh/ssh_host_ed25519_key
SetEnv http_proxy=http://egress:8888 https_proxy=http://egress:8888
Subsystem sftp internal-sftp
""")
        known_hosts.append(
            f"{container.name} {container.host_pub.read_text().strip()}\n"
        )
    agent_hosts.write_text("".join(known_hosts))

    # Distribute keys.
    for container in containers:
        dev = f"{container.path}/dev"
        check_call_verbose(["ssh", container.host, "mkdir", "-p", f"{dev}/"])
        check_call_verbose(
            [
                "rsync",
                "-avz",
                "--delete",
                f"{BASEDIR / 'dev'}/",
                f"{container.host}:{dev}/",
            ]
        )
        check_call_verbose(
            [
                "rsync",
                "-avz",
                "--delete",
                f"{container.dev_ssh}/",
                f"{container.host}:{dev}/home/.ssh/",
            ]
        )


if __name__ == "__main__":
    main()
