services:
  dev:
    build: .
    command: ["sleep", "infinity"]
    environment:
      HOST_GID: $GID
      HOST_UID: $UID
      http_proxy: http://egress:8888
      https_proxy: http://egress:8888
    init: true
    hostname: dev
    networks: [walled]
    dns: ["0.0.0.0"]
    volumes:
      - ./home:/home/user
      - ../src:/home/user/src
    depends_on: [egress, tunnel]
  egress:
    build: ./egress
    hostname: egress
    networks:
      walled:
        driver_opts:
          com.docker.network.endpoint.ifname: walled0
      outside: {}
  tunnel:
    build: ./tunnel
    environment:
      HOST_GID: $GID
      HOST_UID: $UID
    init: true
    networks: [outside]
    volumes:
      - $HOME/.ssh:/home/user/.ssh:ro
      - ./home/.ssh:/sockets
      - ./tunnels.yml:/tunnels.yml:ro
networks:
  walled:
    internal: true
  outside: {}
