services:
  dev:
    build: .
    environment:
      HOST_GID: $GID
      HOST_UID: $UID
      http_proxy: http://egress:8888
      https_proxy: http://egress:8888
    hostname: dev
    networks: [walled]
    dns: ["0.0.0.0"]
    extra_hosts:
      - "egress:10.88.0.2"
    volumes:
      - ./home:/home/user
      - ../src:/home/user/src
      - $HOME/.cache/ccache:/home/user/.cache/ccache
      - $HOME/.cache/pip:/home/user/.cache/pip
    depends_on: [egress]
  egress:
    build: ./egress
    hostname: egress
    networks:
      walled:
        ipv4_address: 10.88.0.2
      outside: {}
networks:
  walled:
    internal: true
    ipam:
      config:
        - subnet: 10.88.0.0/24
  outside: {}
