#!/usr/bin/env python3
import sys
from os import environ, getgid, getuid
from os.path import exists
from pathlib import Path
from subprocess import call, check_call


def call_verbose(argv, **kwargs):
    print("+", argv, file=sys.stderr)
    return call(argv, **kwargs)


def check_call_verbose(argv, **kwargs):
    print("+", argv, file=sys.stderr)
    check_call(argv, **kwargs)


def main():
    dev_dir = Path(sys.argv[0]).parent
    env = {
        **environ,
        "UID": str(getuid()),
        "GID": str(getgid()),
    }
    if exists("/dev/kvm"):
        env["KVM_GID"] = str(Path("/dev/kvm").stat().st_gid)

    try:
        status = call_verbose(
            ["docker", "compose", "run", "--build", "--remove-orphans", "dev"],
            cwd=dev_dir,
            env=env,
        )
    finally:
        check_call_verbose(
            ["docker", "compose", "down"],
            cwd=dev_dir,
            env=env,
        )
    sys.exit(status)


if __name__ == "__main__":
    main()
