#!/usr/bin/env python3
"""Build and start the dev containers in the background."""

import sys
from os import environ, getgid, getuid
from os.path import exists
from pathlib import Path
from subprocess import check_call


def check_call_verbose(argv, **kwargs):
    print("+", argv, file=sys.stderr)
    check_call(argv, **kwargs)


def main():
    dev_dir = Path(sys.argv[0]).parent
    env = {
        **environ,
        "UID": str(getuid()),
        "GID": str(getgid()),
    }
    if exists("/dev/kvm"):
        env["KVM_GID"] = str(Path("/dev/kvm").stat().st_gid)
    check_call_verbose(
        ["docker", "compose", "up", "--build", "--remove-orphans", "--wait"],
        cwd=dev_dir,
        env=env,
    )


if __name__ == "__main__":
    main()
