services:
  common:
    build: ./common
  agent:
    build:
      additional_contexts:
        base: "service:common"
    environment:
      HOST_GID: $GID
      HOST_UID: $UID
      http_proxy: http://egress:8888
      https_proxy: http://egress:8888
      REVIEW_PROMPTS_PROJECT: $REVIEW_PROMPTS_PROJECT
    hostname: agent
    networks: [walled]
    dns: ["0.0.0.0"]
    volumes:
      - ./home:/home/user
      - $PROJECT_DIR/src:/home/user/src
      - $PROJECT_DIR/.git:/home/user/.git
      - $PROJECT_DIR/.gitmodules:/home/user/.gitmodules
    working_dir: /home/user/$WORKING_DIR
    depends_on: [egress]
  egress:
    build: ./egress
    hostname: egress
    networks:
      walled:
        driver_opts:
          com.docker.network.endpoint.ifname: walled0
      outside: {}
networks:
  walled:
    internal: true
  outside: {}
